name: Lighthouse Check
on:
  push:
    branches:
      - master
  pull_request:
    branches: []

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@master
      -   run: mkdir /tmp/artifacts

      -   name: Start angular
          run: |
              docker build -t questophant-frontend .
              docker run -p 80:80 -p 443:443 -d questophant-frontend

      -   name: Run Lighthouse
          uses: foo-software/lighthouse-check-action@master
          with:
              accessToken: ${{ secrets.LIGHTHOUSE_ACTION_ACCESS_TOKEN }}
              outputDirectory: /tmp/artifacts
              urls: 'http://localhost'
              prCommentEnabled: true
              prCommentSaveOld: true

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
